sudo: required

language: c

services:
  - docker

# This will change in the future
before_install:
  - docker info
  - docker build -t anonymint/alpine-openjdk .

script:
  - docker run -it --rm anonymint/alpine-openjdk